import json
import os
from pathlib import Path
from types import SimpleNamespace

import pytest
from robotics_dockers.config import ROS_DISTROS

import ros_project_generator.cli as cli_module
import ros_project_generator.create_ros_project as create_ros_project_module
import ros_project_generator.create_vscode_project as create_vscode_project_module
import ros_project_generator.ros_project_generator as ros_project_generator_module
from ros_project_generator.ros_project_generator import RosProjectCreator, RosProjectCreatorException
from ros_project_generator.utilities import Utilities
from ros_project_generator.vscode_project_creator import VscodeProjectCreator, VscodeProjectCreatorException


@pytest.fixture
def fake_active_user(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    user_home = tmp_path / 'home'
    user_home.mkdir()

    monkeypatch.setenv('USER', 'developer')
    monkeypatch.delenv('SUDO_USER', raising=False)
    monkeypatch.setattr(
        ros_project_generator_module.pwd, 'getpwnam', lambda username: SimpleNamespace(pw_dir=str(user_home))
    )

    return user_home


@pytest.fixture
def fake_docker_generator(monkeypatch: pytest.MonkeyPatch):
    calls = []

    def generate_docker_context(config):
        calls.append(config)
        output_dir = Path(config.output_dir)
        output_dir.mkdir(parents=True)
        output_dir.joinpath('Dockerfile').write_text('# generated by robotics_dockers\n')
        output_dir.joinpath('build.py').write_text('# generated by robotics_dockers\n')
        output_dir.joinpath('docker-compose-dev.yaml').write_text(
            'services:\n  demo_latest_cont:\n    image: demo:latest\n'
        )
        output_dir.joinpath('.resources').mkdir()
        return SimpleNamespace(
            context_dir=output_dir,
            resolved_config=SimpleNamespace(
                user=config.user,
                user_id=int(config.user_id),
                primary_group=config.primary_group or config.user,
                primary_group_id=int(config.primary_group_id),
            ),
        )

    monkeypatch.setattr(ros_project_generator_module, 'generate_docker_context', generate_docker_context)
    return calls


def _create_project(project_dir: Path, **overrides) -> None:
    arguments = {
        'project_id': 'demo',
        'project_dir': project_dir,
        'user': 'developer',
        'user_id': '1001',
        'primary_group': 'robotics',
        'primary_group_id': '1002',
        'ros_distro': 'jazzy',
        'base_img': 'ubuntu:24.04',
        'img_id': 'demo:latest',
        'use_vscode_project': False,
        'use_pre_commit': False,
        'use_console_log': False,
    }
    arguments.update(overrides)
    RosProjectCreator(**arguments)


def test_ros_variants_match_robotics_dockers_supported_ubuntu_versions() -> None:
    variants_file = Path(ros_project_generator_module.__file__).parent.joinpath('resources/ros/ros_variants.yaml')
    variants = Utilities.load_yaml(variants_file)

    assert {distro: values['ubuntu_version'] for distro, values in variants.items()} == ROS_DISTROS


def test_create_ros2_project_delegates_docker_generation(fake_active_user: Path, fake_docker_generator) -> None:
    project_dir = fake_active_user / 'demo_project'

    _create_project(project_dir)

    assert len(fake_docker_generator) == 1
    docker_config = fake_docker_generator[0]
    assert docker_config.user == 'developer'
    assert docker_config.user_id == '1001'
    assert docker_config.primary_group == 'robotics'
    assert docker_config.primary_group_id == '1002'
    assert docker_config.ros_distro == 'jazzy'
    assert docker_config.img_id == 'demo:latest'
    assert docker_config.output_dir == project_dir / 'docker'
    assert docker_config.rosdep_packages_dir == '../src'

    assert project_dir.joinpath('docker/Dockerfile').is_file()
    assert project_dir.joinpath('docker/build.py').is_file()
    assert project_dir.joinpath('docker/docker-compose-dev.yaml').is_file()
    assert project_dir.joinpath('docker/.resources').is_dir()

    assert project_dir.joinpath('deps.repos').is_file()
    assert project_dir.joinpath('src/0_deps').is_dir()
    assert project_dir.joinpath('src/bringup/package.xml').is_file()
    assert project_dir.joinpath('src/simulation/package.xml').is_file()


def test_create_ros2_project_with_vscode_copies_the_robotics_dockers_compose(fake_active_user: Path) -> None:
    project_dir = fake_active_user / 'demo_vscode'

    _create_project(project_dir, img_id='demo/vscode:latest', use_vscode_project=True)

    docker_compose = project_dir / 'docker/docker-compose-dev.yaml'
    devcontainer_compose = project_dir / '.devcontainer/docker-compose.yaml'
    devcontainer_file = project_dir / '.devcontainer/devcontainer.json'
    code_devcont_script = project_dir / '.devcontainer/code-devcont'
    devcont_script = project_dir / '.devcontainer/devcont'

    for generated_file in (
        devcontainer_file,
        code_devcont_script,
        devcont_script,
        devcontainer_compose,
        project_dir / '.vscode/c_cpp_properties.json',
        project_dir / '.vscode/tasks.json',
        project_dir / 'ws.code-workspace',
    ):
        assert generated_file.is_file()
        assert '{{' not in generated_file.read_text()
        assert '}}' not in generated_file.read_text()

    # Both use cases receive the same complete runtime configuration. They are
    # separate files so a developer can later customize only .devcontainer.
    assert devcontainer_compose.read_bytes() == docker_compose.read_bytes()

    compose_text = devcontainer_compose.read_text()
    assert 'demo/vscode:latest' in compose_text
    assert '${HOST_ROS_WORKSPACE:' in compose_text
    assert ':/workspace' in compose_text
    assert '/run/user/1001:mode=700,uid=1001,gid=1002' in compose_text
    assert 'XDG_RUNTIME_DIR: "/run/user/1001"' in compose_text
    assert 'CONTAINER_ROS_WORKSPACE: "/workspace"' in compose_text
    assert '# cap_add:' in compose_text
    assert '#   - NET_ADMIN' in compose_text
    assert 'HOST_UID' not in compose_text
    assert 'HOST_UPGID' not in compose_text
    assert 'user: root' not in compose_text
    assert 'driver: nvidia' not in compose_text

    devcontainer = json.loads(devcontainer_file.read_text())
    assert devcontainer['dockerComposeFile'] == 'docker-compose.yaml'
    assert devcontainer['service'] == 'demo_vscode_latest_cont'
    assert devcontainer['updateRemoteUserUID'] is False
    assert devcontainer['overrideCommand'] is False
    assert 'containerUser' not in devcontainer
    assert devcontainer['remoteUser'] == 'developer'
    assert devcontainer['workspaceFolder'] == '/workspace'

    assert os.access(code_devcont_script, os.X_OK)
    assert os.access(devcont_script, os.X_OK)
    assert 'HOST_ROS_WORKSPACE' in code_devcont_script.read_text()
    assert 'HOST_ROS_WORKSPACE' in devcont_script.read_text()
    assert 'HOST_UID' not in code_devcont_script.read_text()
    assert 'HOST_UPGID' not in devcont_script.read_text()
    assert not project_dir.joinpath('.devcontainer/.env').exists()


def test_devcontainer_compose_is_independent_after_initial_copy(fake_active_user: Path) -> None:
    project_dir = fake_active_user / 'independent_compose'
    _create_project(project_dir, use_vscode_project=True)

    docker_compose = project_dir / 'docker/docker-compose-dev.yaml'
    devcontainer_compose = project_dir / '.devcontainer/docker-compose.yaml'
    original_docker_compose = docker_compose.read_text()

    devcontainer_compose.write_text(devcontainer_compose.read_text() + '\n# Local developer customization.\n')

    assert docker_compose.read_text() == original_docker_compose
    assert devcontainer_compose.read_text() != docker_compose.read_text()


def test_nvidia_configuration_is_copied_when_requested(fake_active_user: Path) -> None:
    project_dir = fake_active_user / 'nvidia_project'
    _create_project(project_dir, use_vscode_project=True, use_host_nvidia_driver=True)

    compose_text = project_dir.joinpath('.devcontainer/docker-compose.yaml').read_text()
    assert 'driver: nvidia' in compose_text
    assert 'capabilities: [gpu]' in compose_text
    assert 'NVIDIA_VISIBLE_DEVICES: "all"' in compose_text
    assert 'NVIDIA_DRIVER_CAPABILITIES: "all"' in compose_text


def test_rejects_unsupported_ros_distro(fake_active_user: Path, fake_docker_generator) -> None:
    with pytest.raises(RosProjectCreatorException, match='Allowed ROS distros'):
        _create_project(fake_active_user / 'noetic', ros_distro='noetic')

    assert fake_docker_generator == []


def test_rejects_blank_project_dir(fake_active_user: Path, fake_docker_generator) -> None:
    with pytest.raises(RosProjectCreatorException, match='Project directory must be a non-empty path'):
        _create_project(Path('   '))

    assert fake_docker_generator == []


def test_rejects_relative_project_dir_outside_active_user_home(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, fake_active_user: Path, fake_docker_generator
) -> None:
    outside_home = tmp_path / 'outside_home'
    outside_home.mkdir()
    monkeypatch.chdir(outside_home)

    with pytest.raises(RosProjectCreatorException, match='Project directory must be inside'):
        _create_project(Path('demo_project'))

    assert fake_docker_generator == []


def test_dot_project_dir_resolves_before_home_check(
    monkeypatch: pytest.MonkeyPatch, fake_active_user: Path, fake_docker_generator
) -> None:
    monkeypatch.chdir(fake_active_user)

    with pytest.raises(RosProjectCreatorException, match='already exists'):
        _create_project(Path('.'))

    assert fake_docker_generator == []


def test_vscode_project_rejects_compose_with_multiple_services(tmp_path: Path) -> None:
    workspace_dir = tmp_path / 'workspace'
    workspace_dir.mkdir()
    compose_file = workspace_dir / 'compose.yaml'
    compose_file.write_text('services:\n  first: {}\n  second: {}\n')

    with pytest.raises(VscodeProjectCreatorException, match='exactly one service'):
        VscodeProjectCreator(
            project_id='demo',
            ros_distro='jazzy',
            user='developer',
            workspace_dir=workspace_dir,
            source_compose_file=compose_file,
            use_console_log=False,
        )


def test_create_ros_project_cli_requires_and_forwards_image_identity(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls = []
    monkeypatch.setattr(create_ros_project_module, 'RosProjectCreator', lambda **kwargs: calls.append(kwargs))

    create_ros_project_module.main(
        [
            'demo',
            str(tmp_path / 'demo'),
            'developer',
            '1001',
            '1002',
            'jazzy',
            '--group',
            'robotics',
            '--base-img',
            'ubuntu:24.04',
        ]
    )

    assert calls[0]['user'] == 'developer'
    assert calls[0]['user_id'] == '1001'
    assert calls[0]['primary_group'] == 'robotics'
    assert calls[0]['primary_group_id'] == '1002'
    assert calls[0]['ros_distro'] == 'jazzy'
    assert calls[0]['base_img'] == 'ubuntu:24.04'


def test_ros_project_cli_new_delegates_to_project_creator(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    calls = []

    def create_project(argv, prog=None):
        calls.append((argv, prog))

    monkeypatch.setattr(cli_module.create_ros_project, 'main', create_project)
    arguments = ['demo', str(tmp_path / 'demo'), 'developer', '1001', '1002', 'jazzy']

    cli_module.main(['new', *arguments])

    assert calls == [(arguments, 'ros-project new')]


def test_create_vscode_project_cli_uses_generated_compose_by_default(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls = []
    workspace_dir = tmp_path / 'workspace'
    monkeypatch.setattr(create_vscode_project_module, 'VscodeProjectCreator', lambda **kwargs: calls.append(kwargs))

    create_vscode_project_module.main(['demo', str(workspace_dir), 'developer', 'jazzy'])

    assert calls[0]['project_id'] == 'demo'
    assert calls[0]['user'] == 'developer'
    assert calls[0]['workspace_dir'] == workspace_dir
    assert calls[0]['source_compose_file'] == workspace_dir / 'docker/docker-compose-dev.yaml'
