# syntax=docker/dockerfile:1

FROM {{ base_img }}

# The following labels adhere to the OCI Image Specification for standardized metadata.
# Reference: https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.title="Project Docker Image" \
    org.opencontainers.image.description="A Docker image for development and testing" \
    org.opencontainers.image.authors="anon"

ENV IMG_USER="{{ img_user }}" \
    ROS_DISTRO="{{ ros_distro }}" \
    ROS_VERSION="{{ ros_version }}" \
    DEBIAN_FRONTEND="noninteractive"

USER root
WORKDIR /

# Using the pattern COPY+RUN we can benefit from Docker's build cache.
# The copied files are lightweight, therefore the size of the associated layer is small.
# The script install_core.sh is responsible for installing system dependencies.
{% if use_host_nvidia_driver %}
COPY --chmod=775 docker/.resources/install_base_system.sh /tmp/
RUN /tmp/install_base_system.sh "${IMG_USER}" "" && rm -rf /tmp/install_base_system.sh
{% else %}
COPY --chmod=775 docker/.resources/install_base_system.sh docker/.resources/install_mesa_packages.sh /tmp/
RUN /tmp/install_base_system.sh "${IMG_USER}" /tmp/install_mesa_packages.sh && rm -rf /tmp/install_base_system.sh  /tmp/install_mesa_packages.sh
{% endif %}

COPY --chmod=775 docker/.resources/install_ros.sh /tmp/
RUN /tmp/install_ros.sh "${IMG_USER}" "${ROS_DISTRO}" "${ROS_VERSION}" && rm -rf /tmp/install_ros.sh

# The following block is always re-executed and is NOT cached intentionally.
# It uses the --mount=type=bind option to bind the current context to the container, since the context has, most of the
# time, a significant amount of files that do not need to be copied, and subsequently occupying space in the associated
# layer.
RUN --mount=type=bind,source=.,target=/tmp/context bash <<'EOF'
log() { echo "[$(date --utc '+%Y-%m-%d_%H-%M-%S')]" "$@"; }

img_user_entry="$(getent passwd "${IMG_USER}")"

if [ -z "${img_user_entry}" ]; then
    log "Error: User '${IMG_USER}' not found" >&2
    exit 1
fi

{% if not use_base_img_entrypoint %}
if [ ! -f /tmp/context/docker/entrypoint.sh ]; then
    log "Error: Script entrypoint.sh not provided" >&2
    exit 1
fi
{% endif %}

{% if use_environment %}
if [ ! -f /tmp/context/docker/.resources/environment.sh ]; then
    log "Error: Script environment.sh not provided" >&2
    exit 1
fi
{% endif %}

if [ ! -f /tmp/context/docker/.resources/deduplicate_path.sh ]; then
    log "Error: Script deduplicate_path.sh not provided" >&2
    exit 1
fi

if [ ! -f /tmp/context/docker/.resources/rosbuild.sh ]; then
    log "Error: Script rosbuild.sh not provided" >&2
    exit 1
fi

if [ ! -f /tmp/context/docker/.resources/rosdep_init_update.sh ]; then
    log "Error: Script rosdep_init_update.sh not provided" >&2
    exit 1
fi

# Check if ${ROS_DISTRO} is installed properly, otherwise abort the installation.
ros_distro=$(dpkg --list | sed -nE 's/^ii\s+ros-([a-z]+)-ros-core.*$/\1/p' | tr '\n' ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

num_distros=$(echo "${ros_distro}" | wc -w)

# If no ROS_DISTRO is found at this point, exit with an error.
if [ "${num_distros}" -eq 0 ]; then
    log "Error: No ROS distribution found" >&2
    exit 1
fi

if [ "${num_distros}" -gt 1 ]; then
    log "Error: More than one ROS_DISTRO found: ${ros_distro}" >&2
    exit 1
fi

if [ "${ROS_DISTRO}" != "${ros_distro}" ]; then
    log "Error: Found ROS_DISTRO '${ros_distro}', expected ROS_DISTRO '${ROS_DISTRO}'" >&2
    exit 1
fi

rosdep_ignored_key_file=/tmp/context/docker/.resources/rosdep_ignored_keys.yaml
src_dir="/tmp/context/src"

# Copy the rosdep initialization script to a temporary location to be able to mark it as executable
# and execute it.
cp /tmp/context/docker/.resources/rosdep_init_update.sh /tmp/rosdep_init_update.sh
chmod 775 /tmp/rosdep_init_update.sh
/tmp/rosdep_init_update.sh "${IMG_USER}" "${ROS_DISTRO}" "${src_dir}" "${rosdep_ignored_key_file}"
rm -f /tmp/rosdep_init_update.sh

if [ -s /tmp/context/docker/.resources/colcon_mixin_metadata.sh ]; then
    # Copy the colcon mixin metadata script to a temporary location to be able to mark it as
    # executable and execute it.
    cp /tmp/context/docker/.resources/colcon_mixin_metadata.sh /tmp/colcon_mixin_metadata.sh
    chmod 775 /tmp/colcon_mixin_metadata.sh
    /tmp/colcon_mixin_metadata.sh "${IMG_USER}"
    rm -f /tmp/colcon_mixin_metadata.sh
else
    log "No colcon_mixin_metadata.sh script found, skipping colcon mixin metadata installation"
fi

# Execute the custom dependency install script for the project.
find "/tmp/context" -maxdepth 1 -type f -name 'install_deps.sh' -exec bash {} \;

img_user_id="$(echo "${img_user_entry}" | cut -d: -f3)"
img_user_pri_group_id="$(echo "${img_user_entry}" | cut -d: -f4)"
img_user_pri_group="$(getent group "${img_user_pri_group_id}" | cut -d: -f1)"
img_user_home="$(echo "${img_user_entry}" | cut -d: -f6)"

# Every file and folder in img_user_home must belong to the IMG_USER.
log "Setting ownership of path '${img_user_home}' to user '${IMG_USER}' (UID '${img_user_id}') and primary group '${img_user_pri_group}' (GID '${img_user_pri_group_id}')"
chown --recursive "${IMG_USER}":"${img_user_pri_group}" "${img_user_home}"

{% if not use_base_img_entrypoint %}
log "Installing file '/usr/local/bin/entrypoint.sh'" >&2
install --owner root --group root --mode 775 /tmp/context/docker/entrypoint.sh /usr/local/bin/entrypoint.sh
{% endif %}

log "Installing file '/usr/local/bin/deduplicate_path.sh'"
install --owner root --group root --mode 775 /tmp/context/docker/.resources/deduplicate_path.sh /usr/local/bin/deduplicate_path.sh

log "Installing file '/usr/local/bin/rosbuild.sh'"
install --owner root --group root --mode 775 /tmp/context/docker/.resources/rosbuild.sh /usr/local/bin/rosbuild.sh

{% if use_environment %}
# An environment script is installed in the home directory of the '${IMG_USER}'.
log "Installing file '${img_user_home}/.environment.sh'"
install --owner "${IMG_USER}" --group "${img_user_pri_group}" --mode 775 /tmp/context/docker/.resources/environment.sh "${img_user_home}/.environment.sh"
{% endif %}

# Optional: install .bash_aliases if present
if [ -e /tmp/context/docker/.resources/dot_bash_aliases ]; then
    install --owner "${IMG_USER}" --group "${img_user_pri_group}" --mode 775 /tmp/context/docker/.resources/dot_bash_aliases "${img_user_home}/.bash_aliases"
fi

log "Removing installation residues from apt cache"
apt-get autoclean
apt-get autoremove --purge -y
apt-get clean
rm -rf /var/lib/apt/lists/* &>/dev/null
EOF

# Configure timezone and localization settings.
# - TZ: Set the timezone to UTC to ensure consistent time handling across environments.
# - LC_ALL, LANG, LANGUAGE: Configure localization to US English and UTF-8 encoding, which helps
#   avoiding issues with character encoding and ensures compatibility with most tools and libraries.
ENV TZ="Etc/UTC" \
    LC_ALL="en_US.UTF-8" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    ROS_HOME="{{ img_user_home }}/.ros" \
    ROS_LOG_DIR="{{ img_user_home }}/.ros/logs" \
    ROS_TEST_RESULTS_DIR="{{ img_user_home }}/.ros/tests" \
    ROS_CONFIG_HOME="{{ img_user_home }}/.config/ros.org" \
{{ extra_ros_env_vars }}

USER "${IMG_USER}"
WORKDIR "/"
{% if not use_base_img_entrypoint -%}
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
{% endif -%}
CMD ["bash"]
